### ISSUE TITLE
Cactus Responsiveness / Feedback Typo

### ISSUE THREAD

**Issue by mike10911** [HackBeanpot/mono-repo#176]
In the FAQ section of the main site (hackbeanpot.com) and in the `main-site` directory under `components/faq-section`, the cactus image at some screen sizes is behind the faq text, resulting in some ugly overlapping.

### Example:

https://user-images.githubusercontent.com/103906123/236979982-4c330b27-7fcb-46ee-aef5-456574ffc4dc.mov

Also in the "Send us your feedback" section of the live site (live.hackbeanpot.com) and in the `live-site` directory under  `components/resources-section`, it mentions "Camp HackBeanpot" which is the 2022 event name.

### Example:
<img width="1190" alt="Screen Shot 2023-05-08 at 10 35 55 PM" src="https://user-images.githubusercontent.com/103906123/236980832-41ec8e48-c33a-427b-8572-147ac7f15301.png">

### Your job is to:

- [ ] Reposition or resized the cactus so that it is never overlapping with text at any screen size
- [ ] Change "Camp HackBeanpot" to "HackBeanpot Desert Exploration"

**Comment by NelsonDong41** [comment]
The typo is not under the live-site directory under components/resources-section but is actually in the components/feedback-join-core-section
