### ISSUE TITLE
Create Judging Tickets Based on Design Doc

### ISSUE THREAD

**Issue by mike10911** [HackBeanpot/mono-repo#179]
title

**Comment by surbhi-gulati** [comment]
@alyssamui  / @mike10911 
Completed and uploaded the 7 tickets after last week's design review + updating the DB strategies from dev / prod DB's to using Docker to use local / singular prod version on HBP cluster for development.

I think we are good to close the issue?

- [Board with the 7 tickets](https://github.com/orgs/HackBeanpot/projects/5/views/3)
- [Design doc](https://docs.google.com/document/d/1BvoLmseirhUWLc4H2NgZVYB84oxghCpwLqq0YBz4vC4/edit)
