### ISSUE TITLE
[Enhancement] Redesign Sponsor Us Page to Under the Sea theme

### ISSUE THREAD

**Issue by mike10911** [HackBeanpot/mono-repo#224]
### TWO WEEK SPIRNT

Based on the new theme design, redesign the Sponsor Us page. The components should be the same, but we need updated colors, images, fonts, etc.

**Acceptance Criteria** 

WEEK 1

- [x] Update desktop designs

WEEK 2

- [x] Update mobile designs

Review by @helenm1 @audrey @mike10911 @crit

**Comment by crit** [comment]
I don't think you meant to add me to this project.
