### ISSUE TITLE
Update Sponsor Perks

### ISSUE THREAD

**Issue by mike10911** [HackBeanpot/mono-repo#336]
[Designs](https://www.figma.com/file/ONkXtJcw5iJL5Az7Mmi64S/Main-Site-Wireframes?type=design&node-id=323-463&mode=design&t=PIjtncHuQ6MnFP4i-0)

Update the sponsor-us perks section to reflect the theme refresh!

AC:

- [ ]  Total responsiveness
- [ ]  Light and dark mode

![Image](https://github.com/HackBeanpot/mono-repo/assets/103906123/a77e6fd6-5207-43f9-a41a-559e7086af1b)
![Image](https://github.com/HackBeanpot/mono-repo/assets/103906123/aaa5f7b6-5401-4b4f-8adc-05513d0a4f79)

Reviewers:
- @NelsonDong41 @Aaryan1203 @agonzalez22

**Comment by yumi520** [comment]
Created sponsor-us perks section and implemented responsiveness.

Fixes https://github.com/HackBeanpot/mono-repo/issues/336#issue-2099056428

Changelist:

added sponsor-us perks section
ensured responsiveness

Tested:

tested on different breakpoints/screen sizes in the browser
still a little wonky

Screenshots & Screencasts:


![Image](https://github.com/HackBeanpot/mono-repo/assets/75456756/ba4157dc-b976-4601-83a3-918b5aed1179)



![Image](https://github.com/HackBeanpot/mono-repo/assets/75456756/b5d3c634-dd56-4ede-aad2-6ede716fe713)



![Image](https://github.com/HackBeanpot/mono-repo/assets/75456756/96d0887a-58c1-4204-b4be-66676340c690)
